name: Windows QGC Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.10.3
        host: windows
        target: desktop
        arch: win64_mingw
        modules: qtmultimedia qtgraphs qtcharts qtshadertools

    - name: Setup build
      shell: bash
      run: |
        mkdir build
        cd build

        cmake .. \
        -G "MinGW Makefiles" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$Qt6_DIR"

    - name: Build QGroundControl
      shell: bash
      run: |
        cd build
        cmake --build . --config Release -j4


    - name: Package EXE
      shell: bash
      run: |
        cd build

        mkdir package

        windeployqt Release/QGroundControl.exe --qmldir ../src

        cp Release/QGroundControl.exe package/


    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: QGroundControl-Windows
        path: build/package
